deploymentName: configserver-deployment
deploymentLabel: configserver
appName: configserver
replicaCount: 1

image:
  repository: madalinaotvos/configserver
  tag: latest

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

config_enabled: false
profile_enabled: true
appname_enabled: true
resouceserver_enabled: false
keycloak_enabled: false
eureka_enabled: false