apiVersion: v1
kind: ConfigMap
metadata:
  name: k8dockerkeycloak
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_ZIPKIN_BASEURL: http://zipkin-service:9411/
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service:9411/api/v2/spans
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
  EUREKA_APPLICATION_NAME: eurekaserver
  APP_APPLICATION_NAME: k8dockerkeycloak
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:8070/eureka/